select count(w_id) from onesql_warehouse;
select count(d_w_id) from onesql_district;
select count(c_w_id) from onesql_customer;
select count(h_c_id) from onesql_history;
select count(no_w_id) from onesql_new_orders;
select count(o_w_id) from onesql_orders;
select count(ol_w_id) from onesql_order_line;
select count(i_id) from onesql_item;
select count(s_w_id) from onesql_stock;
